version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo "Upgrade Pip and install packages."
      - make install

  pre_build:
    commands:
      - mkdir -p build

  build:
    commands:
      - cp wine_predict/wine_quality_predict-sagemaker-SKLearn-build-test.ipynb  /build
      - echo "Starting packaging `date` in `pwd`"
      - make lint

  post_build:
    commands:
       - echo 'Running Notebook'
       - pwd
       - ls
       - runipy /build/wine_quality_predict-sagemaker-SKLearn-build-test.ipynb

#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths